/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated from the OpenAPI specification.
 * To regenerate, run: yarn generate-schemas
 *
 * Source: https://sweepsteak-production--sweepsteak-64dd0.europe-west4.hosted.app/openapi.json
 * Generated: 2025-11-18T12:58:19.479Z
 *
 * Note: Schemas are intentionally relaxed (optional fields, flexible types)
 * to handle real-world API responses gracefully.
 */

import { z } from 'zod';

// User
export const userSchema = z.object({
  id: z.string().optional(),
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  nickname: z.string().optional(),
  email: z.string().optional(),
  bio: z.string().optional(),
  profile_picture: z.string().optional(),
  phone_number: z.string().optional(),
  game_stop_id: z.string().optional(),
  is_auth_verified: z.boolean().optional(),
  is_identity_verified: z.boolean().optional(),
  deposit_limit: z
    .object({
      daily: z.number().optional(),
      weekly: z.number().optional(),
      monthly: z.number().optional(),
    })
    .optional(),
  betting_limit: z.number().optional(),
  payment_id: z.string().optional(),
  current_balance: z.number().optional(),
  is_self_excluded: z.boolean().optional(),
  is_admin: z.boolean().optional(),
  kyc_completed: z.boolean().optional(),
  kyc_instance_id: z.string().optional(),
  exclusion_ending: z.string().optional(),
  address: z
    .object({
      line1: z.string().optional(),
      line2: z.string().optional(),
      line3: z.string().optional(),
      town: z.string().optional(),
      county: z.string().optional(),
      postcode: z.string().optional(),
      country: z.string().optional(),
    })
    .optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  status: z.string().optional(),
});

export type User = z.infer<typeof userSchema>;

// Tournament
export const tournamentSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  starts_at: z.string().optional(),
  finishes_at: z.string().optional(),
  description: z.string().optional(),
  url: z.string().optional(),
  cover_picture: z.string().optional(),
  gallery: z.array(z.string()).optional().default([]),
  holes: z
    .array(
      z.object({
        id: z.string().optional(),
        name: z.string().optional(),
        description: z.string().optional(),
        position: z.number().optional(),
        cover_image: z.string().optional(),
        par: z.number().optional(),
        distance: z.number().optional(),
        created_at: z.string().optional(),
        updated_at: z.string().optional(),
      }),
    )
    .optional()
    .default([]),
  ads: z
    .array(
      z.object({
        id: z.string().optional(),
        name: z.string().optional(),
        description: z.string().optional(),
        position: z.number().optional(),
        website: z.string().optional(),
        created_at: z.string().optional(),
        updated_at: z.string().optional(),
      }),
    )
    .optional()
    .default([]),
  proposed_entry_fee: z.number().optional(),
  maximum_cut_amount: z.number().optional(),
  maximum_score_generator: z.number().optional(),
  players: z
    .array(
      z.object({
        id: z.string().optional(),
        external_id: z.string().optional(),
        level: z.number().optional(),
        current_score: z.number().optional(),
        position: z.number().optional(),
        attempts: z
          .object({ hole1: z.number().optional(), hole2: z.number().optional() })
          .optional(),
        missed_cut: z.boolean().optional(),
        odds: z.number().optional(),
        profile_id: z.string().optional(),
        created_at: z.string().optional(),
        updated_at: z.string().optional(),
      }),
    )
    .optional()
    .default([]),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  colours: z
    .object({
      primary: z.string().optional(),
      secondary: z.string().optional(),
      highlight: z.string().optional(),
    })
    .optional(),
  sport: z.string().optional(),
  rules: z.array(z.string()).optional().default([]),
  instructions: z.array(z.string()).optional().default([]),
});

export type Tournament = z.infer<typeof tournamentSchema>;

// Team
export const teamSchema = z.object({
  league: z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      description: z.string().optional(),
      entry_fee: z.number().optional(),
      contact_phone: z.string().optional(),
      contact_email: z.string().optional(),
      contact_visibility: z.boolean().optional(),
      max_participants: z.number().optional(),
      rewards: z.array(z.object({})).optional().default([]),
      start_time: z.string().optional(),
      end_time: z.string().optional(),
      type: z.string().optional(),
      user_id_list: z.array(z.string()).optional().default([]),
      tournament_id: z.string().optional(),
      owner_id: z.string().optional(),
      created_at: z.string().optional(),
      updated_at: z.string().optional(),
    })
    .optional(),
  team: z
    .object({
      id: z.string().optional(),
      owner_id: z.string().optional(),
      player_ids: z.array(z.string()).optional().default([]),
      created_at: z.string().optional(),
      updated_at: z.string().optional(),
    })
    .optional(),
  players: z
    .array(
      z.object({
        id: z.string().optional(),
        external_id: z.string().optional(),
        level: z.number().optional(),
        current_score: z.number().optional(),
        position: z.number().optional(),
        attempts: z.record(z.string(), z.number()).optional(),
        missed_cut: z.boolean().optional(),
        odds: z.number().optional(),
        profile_id: z.string().optional(),
        created_at: z.string().optional(),
        updated_at: z.string().optional(),
      }),
    )
    .optional()
    .default([]),
});

export type Team = z.infer<typeof teamSchema>;

// League
export const leagueSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  entry_fee: z.number().optional(),
  contact_phone: z.string().optional(),
  contact_email: z.string().optional(),
  contact_visibility: z.boolean().optional(),
  max_participants: z.number().optional(),
  rewards: z.array(z.object({})).optional().default([]),
  start_time: z.string().optional(),
  end_time: z.string().optional(),
  type: z.string().optional(),
  user_id_list: z.array(z.string()).optional().default([]),
  tournament_id: z.string().optional(),
  owner_id: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  league: z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      description: z.string().optional(),
      entry_fee: z.number().optional(),
      contact_phone: z.string().optional(),
      contact_email: z.string().optional(),
      contact_visibility: z.boolean().optional(),
      max_participants: z.number().optional(),
      rewards: z.array(z.object({})).optional().default([]),
      start_time: z.string().optional(),
      end_time: z.string().optional(),
      type: z.string().optional(),
      user_id_list: z.array(z.string()).optional().default([]),
      tournament_id: z.string().optional(),
      owner_id: z.string().optional(),
      created_at: z.string().optional(),
      updated_at: z.string().optional(),
    })
    .optional(),
  tournament: z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      starts_at: z.string().optional(),
      finishes_at: z.string().optional(),
      description: z.string().optional(),
      url: z.string().optional(),
      cover_picture: z.string().optional(),
      gallery: z.array(z.string()).optional().default([]),
      holes: z
        .array(
          z.object({
            id: z.string().optional(),
            name: z.string().optional(),
            description: z.string().optional(),
            position: z.number().optional(),
            cover_image: z.string().optional(),
            par: z.number().optional(),
            distance: z.number().optional(),
            created_at: z.string().optional(),
            updated_at: z.string().optional(),
          }),
        )
        .optional()
        .default([]),
      ads: z
        .array(
          z.object({
            id: z.string().optional(),
            name: z.string().optional(),
            description: z.string().optional(),
            position: z.number().optional(),
            website: z.string().optional(),
            created_at: z.string().optional(),
            updated_at: z.string().optional(),
          }),
        )
        .optional()
        .default([]),
      proposed_entry_fee: z.number().optional(),
      maximum_cut_amount: z.number().optional(),
      maximum_score_generator: z.number().optional(),
      players: z.array(z.string()).optional().default([]),
      colours: z
        .object({
          primary: z.string().optional(),
          secondary: z.string().optional(),
          highlight: z.string().optional(),
        })
        .optional(),
      sport: z.string().optional(),
      rules: z.array(z.string()).optional().default([]),
      instructions: z.array(z.string()).optional().default([]),
      created_at: z.string().optional(),
      updated_at: z.string().optional(),
    })
    .optional(),
  user_bets: z
    .array(
      z.object({
        id: z.string().optional(),
        owner_id: z.string().optional(),
        league_id: z.string().optional(),
        team_id: z.string().optional(),
        amount: z.number().optional(),
        status: z.string().optional(),
        created_at: z.string().optional(),
        updated_at: z.string().optional(),
      }),
    )
    .optional()
    .default([]),
});

export type League = z.infer<typeof leagueSchema>;

// Bet
export const betSchema = z.object({
  id: z.string().optional(),
  owner_id: z.string().optional(),
  league_id: z.string().optional(),
  team_id: z.string().optional(),
  amount: z.number().optional(),
  status: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export type Bet = z.infer<typeof betSchema>;

// PlayerProfile
export const playerProfileSchema = z.object({
  id: z.string().optional(),
  external_id: z.string().optional(),
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  country: z.string().optional(),
  age: z.number().optional(),
  ranking: z.number().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export type PlayerProfile = z.infer<typeof playerProfileSchema>;

// Transaction
export const transactionSchema = z.object({
  deposited: z.number().optional(),
  withdrawn: z.number().optional(),
  net_profit: z.number().optional(),
  transactions: z
    .array(
      z.object({
        id: z.string().optional(),
        name: z.string().optional(),
        value: z.number().optional(),
        type: z.string().optional(),
        charge_id: z.string().optional(),
        user_id: z.string().optional(),
        created_at: z.string().optional(),
        updated_at: z.string().optional(),
      }),
    )
    .optional()
    .default([]),
  id: z.string().optional(),
  name: z.string().optional(),
  value: z.number().optional(),
  type: z.string().optional(),
  charge_id: z.string().optional(),
  user_id: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export type Transaction = z.infer<typeof transactionSchema>;

// Activitie
export const activitieSchema = z.object({
  deposited: z.number().optional(),
  withdrawn: z.number().optional(),
  net_profit: z.number().optional(),
  transactions: z
    .array(
      z.object({
        id: z.string().optional(),
        name: z.string().optional(),
        value: z.number().optional(),
        type: z.string().optional(),
        charge_id: z.string().optional(),
        user_id: z.string().optional(),
        created_at: z.string().optional(),
        updated_at: z.string().optional(),
      }),
    )
    .optional()
    .default([]),
});

export type Activitie = z.infer<typeof activitieSchema>;

// Player
export const playerSchema = z.object({
  id: z.string().optional(),
  external_id: z.string().optional(),
  level: z.number().optional(),
  current_score: z.number().optional(),
  position: z.number().optional(),
  attempts: z.record(z.string(), z.number()).optional(),
  missed_cut: z.boolean().optional(),
  odds: z.number().optional(),
  profile_id: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export type Player = z.infer<typeof playerSchema>;

// API Response Wrappers
export const usersResponseSchema = z.object({
  data: z.array(userSchema),
});

export type UsersResponse = z.infer<typeof usersResponseSchema>;

export const tournamentsResponseSchema = z.object({
  data: z.array(tournamentSchema),
});

export type TournamentsResponse = z.infer<typeof tournamentsResponseSchema>;

export const teamsResponseSchema = z.object({
  data: z.array(teamSchema),
});

export type TeamsResponse = z.infer<typeof teamsResponseSchema>;

export const leaguesResponseSchema = z.object({
  data: z.array(leagueSchema),
});

export type LeaguesResponse = z.infer<typeof leaguesResponseSchema>;

export const betsResponseSchema = z.object({
  data: z.array(betSchema),
});

export type BetsResponse = z.infer<typeof betsResponseSchema>;

export const playerprofilesResponseSchema = z.object({
  data: z.array(playerProfileSchema),
});

export type PlayerProfilesResponse = z.infer<typeof playerprofilesResponseSchema>;

export const transactionsResponseSchema = z.object({
  data: z.array(transactionSchema),
});

export type TransactionsResponse = z.infer<typeof transactionsResponseSchema>;

export const activitiesResponseSchema = z.object({
  data: z.array(activitieSchema),
});

export type ActivitiesResponse = z.infer<typeof activitiesResponseSchema>;

export const playersResponseSchema = z.object({
  data: z.array(playerSchema),
});

export type PlayersResponse = z.infer<typeof playersResponseSchema>;
