// Leagues list mock data
// Based on API schema: POST/GET /api/games/
export const leaguesListMock = {
  data: [
    {
      id: '1',
      name: 'Memnons GOLF',
      description: 'Join the biggest Masters sweepstake of the season!',
      tournament_id: 'tournament-1',
      entry_fee: 785,
      join_code: '34634',
      max_participants: 100,
      current_participants: 43,
      contact_phone: '+44 7700 900000',
      contact_email: 'memnon@sweepsteak.com',
      contact_visibility: 'public',
      rewards: [
        { position: 1, amount: 200000, percentage: 60 },
        { position: 2, amount: 100000, percentage: 30 },
        { position: 3, amount: 35973, percentage: 10 },
      ],
      start_time: '2026-04-09T08:00:00Z',
      end_time: '2026-04-12T20:00:00Z',
      type: 'public',
      is_featured: true,
      owner_id: 'user-123',
      user_id_list: ['user-123', 'user-456', 'user-789'],
      created_at: '2025-10-01T10:00:00Z',
      updated_at: '2025-10-20T15:30:00Z',
    },
    {
      id: '2',
      name: 'Pauls PinLads',
      description: 'Private league for the pin seekers',
      tournament_id: 'tournament-1',
      entry_fee: 567,
      join_code: '33634',
      max_participants: 80,
      current_participants: 51,
      contact_phone: '+44 7700 900001',
      contact_email: 'paul@sweepsteak.com',
      contact_visibility: 'participants',
      rewards: [
        { position: 1, amount: 171252, percentage: 60 },
        { position: 2, amount: 85626, percentage: 30 },
        { position: 3, amount: 28542, percentage: 10 },
      ],
      start_time: '2026-04-09T08:00:00Z',
      end_time: '2026-04-12T20:00:00Z',
      type: 'public',
      is_featured: false,
      owner_id: 'user-456',
      user_id_list: ['user-456'],
      created_at: '2025-10-02T12:00:00Z',
      updated_at: '2025-10-21T09:15:00Z',
    },
    {
      id: '3',
      name: 'BIG Johns League',
      description: 'Go big or go home!',
      tournament_id: 'tournament-1',
      entry_fee: 1200,
      join_code: '34634',
      max_participants: 50,
      current_participants: 24,
      contact_phone: null,
      contact_email: 'bigjohn@sweepsteak.com',
      contact_visibility: 'private',
      rewards: [
        { position: 1, amount: 113700, percentage: 60 },
        { position: 2, amount: 56850, percentage: 30 },
        { position: 3, amount: 18950, percentage: 10 },
      ],
      start_time: '2026-04-09T08:00:00Z',
      end_time: '2026-04-12T20:00:00Z',
      type: 'private',
      is_featured: false,
      owner_id: 'user-789',
      user_id_list: ['user-789'],
      created_at: '2025-10-03T14:30:00Z',
      updated_at: '2025-10-20T11:00:00Z',
    },
    {
      id: '4',
      name: 'KING GOLF',
      description: 'For the kings of the course',
      tournament_id: 'tournament-2',
      entry_fee: 450,
      join_code: '33634',
      max_participants: 40,
      current_participants: 22,
      contact_phone: '+44 7700 900003',
      contact_email: null,
      contact_visibility: 'public',
      rewards: [
        { position: 1, amount: 75534, percentage: 60 },
        { position: 2, amount: 37767, percentage: 30 },
        { position: 3, amount: 12589, percentage: 10 },
      ],
      start_time: '2026-06-12T08:00:00Z',
      end_time: '2026-06-15T20:00:00Z',
      type: 'public',
      is_featured: true,
      owner_id: 'user-321',
      user_id_list: ['user-321'],
      created_at: '2025-10-04T16:45:00Z',
      updated_at: '2025-10-19T13:20:00Z',
    },
  ],
};

// Single league detail mock
export const leagueDetailMock = {
  data: {
    league: {
      id: '1',
      name: 'Memnons GOLF',
      description: 'Join the biggest Masters sweepstake of the season!',
      tournament_id: 'tournament-1',
      entry_fee: 785,
      join_code: '34634',
      max_participants: 100,
      current_participants: 43,
      total_pot: 33755, // Prize pool
      total_team_count: 43, // Total teams in league
      user_team_count: 2, // Current user's teams
      contact_phone: '+44 7700 900000',
      contact_email: 'memnon@sweepsteak.com',
      contact_visibility: 'public',
      rewards: [
        { position: 1, amount: 200000, percentage: 60 },
        { position: 2, amount: 100000, percentage: 30 },
        { position: 3, amount: 35973, percentage: 10 },
      ],
      start_time: '2026-04-09T08:00:00Z',
      end_time: '2026-04-12T20:00:00Z',
      type: 'public',
      is_featured: true,
      owner_id: 'user-123',
      user_id_list: ['user-123', 'user-456', 'user-789'],
      created_at: '2025-10-01T10:00:00Z',
      updated_at: '2025-10-20T15:30:00Z',
      tournament: {
        id: 'tournament-1',
        name: 'The Masters',
        starts_at: '2026-04-09T08:00:00.000Z',
        finishes_at: '2026-04-12T18:00:00.000Z',
        description: "The Masters Tournament, one of golf's four major championships.",
        url: 'https://example.com/masters',
        cover_picture: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=400',
        gallery: [],
        holes: [
          {
            id: 'hole-1',
            name: 'Hole 1',
            description: 'A challenging par 4 to start the round',
            position: 1,
            cover_image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=400',
            par: 4,
            distance: 445,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          },
          {
            id: 'hole-2',
            name: 'Hole 2',
            description: 'Tricky par 5 with water hazard',
            position: 2,
            cover_image: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400',
            par: 5,
            distance: 575,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          },
          {
            id: 'hole-3',
            name: 'Hole 3',
            description: 'Short but precise par 3',
            position: 3,
            cover_image: 'https://images.unsplash.com/photo-1592919505780-303950717480?w=400',
            par: 3,
            distance: 170,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          },
        ],
        ads: [
          {
            id: 'ad-1',
            name: 'Premium Golf Equipment',
            description: 'Get 20% off on all golf clubs this week!',
            position: 1,
            website: 'https://example.com/golf-shop',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          },
          {
            id: 'ad-2',
            name: 'Golf Resort & Spa',
            description: 'Book your next golf vacation with us',
            position: 2,
            website: 'https://example.com/golf-resort',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          },
        ],
        proposed_entry_fee: 100,
        maximum_cut_amount: 50,
        maximum_score_generator: 100,
        players: [
          {
            id: 'player-1',
            external_id: 'ext-001',
            level: 1,
            current_score: -5,
            position: 1,
            attempts: { hole1: 4, hole2: 5 },
            missed_cut: false,
            odds: 12.5,
            profile_id: 'profile-001',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          },
          {
            id: 'player-2',
            external_id: 'ext-002',
            level: 2,
            current_score: -3,
            position: 2,
            attempts: { hole1: 3, hole2: 4 },
            missed_cut: false,
            odds: 15.0,
            profile_id: 'profile-002',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          },
          {
            id: 'player-3',
            external_id: 'ext-003',
            level: 1,
            current_score: -2,
            position: 3,
            attempts: { hole1: 4, hole2: 6 },
            missed_cut: false,
            odds: 18.0,
            profile_id: 'profile-003',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          },
        ],
        rules: [
          'Each player must select their team before the tournament starts',
          'Points are awarded based on player performance in each round',
          'The player with the highest total score at the end wins',
          'In case of a tie, the player who entered first wins',
        ],
        instructions: [
          'Select your team of golfers from the available players',
          'Monitor live scores and leaderboards during the tournament',
          'Track your position on the league leaderboard',
          'Prizes are awarded to top finishers at tournament completion',
        ],
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
    user_bets: [],
  },
};

// Create league success mock
export const createLeagueSuccessMock = {
  data: {
    id: 'new-league-123',
    name: 'My Private League',
    description: 'Private league for friends',
    tournament_id: 'tournament-1',
    entry_fee: 40,
    join_code: 'c7jxpt',
    max_participants: 3,
    current_participants: 0,
    contact_phone: '+44 7700 900999',
    contact_email: 'user@sweepsteak.com',
    contact_visibility: 'participants',
    rewards: [
      { position: 1, amount: 72, percentage: 60 },
      { position: 2, amount: 36, percentage: 30 },
      { position: 3, amount: 12, percentage: 10 },
    ],
    start_time: '2026-04-09T08:00:00Z',
    end_time: '2026-04-12T20:00:00Z',
    type: 'private',
    is_featured: false,
    owner_id: 'current-user',
    user_id_list: ['current-user'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    auto_join_link: 'https://sweepsteak.com/join/c7jxpt',
  },
};

// Join league success mock
export const joinLeagueSuccessMock = {
  data: {
    success: true,
    message: 'Successfully joined the league',
    leagueId: '1',
  },
};

// Error mocks
export const leagueNotFoundMock = {
  error: 'League not found',
};

export const leagueFullMock = {
  error: 'League is full',
};

export const invalidLeagueCodeMock = {
  error: 'Invalid league code',
};

export const alreadyJoinedMock = {
  error: 'You have already joined this league',
};

export const leagueServerErrorMock = {
  error: 'Failed to process request',
};
