// Player profiles mock data
// Based on API schema: GET /api/player-profiles/

export const playerProfilesListMock = {
  data: [
    {
      id: 'profile-001',
      external_id: 'pga-001',
      first_name: 'Tiger',
      last_name: 'Woods',
      country: 'US',
      age: 48,
      ranking: 1,
      profile_picture: 'https://i.pravatar.cc/150?img=12',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-002',
      external_id: 'pga-002',
      first_name: 'Rory',
      last_name: 'McIlroy',
      country: 'GB',
      age: 35,
      ranking: 2,
      profile_picture: 'https://i.pravatar.cc/150?img=13',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-003',
      external_id: 'pga-003',
      first_name: 'Jon',
      last_name: 'Rahm',
      country: 'ES',
      age: 29,
      ranking: 3,
      profile_picture: 'https://i.pravatar.cc/150?img=14',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-004',
      external_id: 'pga-004',
      first_name: 'Scottie',
      last_name: 'Scheffler',
      country: 'US',
      age: 27,
      ranking: 4,
      profile_picture: 'https://i.pravatar.cc/150?img=15',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-005',
      external_id: 'pga-005',
      first_name: 'Viktor',
      last_name: 'Hovland',
      country: 'NO',
      age: 26,
      ranking: 5,
      profile_picture: 'https://i.pravatar.cc/150?img=33',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-006',
      external_id: 'pga-006',
      first_name: 'Dustin',
      last_name: 'Johnson',
      country: 'US',
      age: 40,
      ranking: 6,
      profile_picture: 'https://i.pravatar.cc/150?img=51',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-007',
      external_id: 'pga-007',
      first_name: 'Collin',
      last_name: 'Morikawa',
      country: 'US',
      age: 27,
      ranking: 7,
      profile_picture: 'https://i.pravatar.cc/150?img=52',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-008',
      external_id: 'pga-008',
      first_name: 'Xander',
      last_name: 'Schauffele',
      country: 'US',
      age: 30,
      ranking: 8,
      profile_picture: 'https://i.pravatar.cc/150?img=56',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-009',
      external_id: 'pga-009',
      first_name: 'Patrick',
      last_name: 'Cantlay',
      country: 'US',
      age: 32,
      ranking: 9,
      profile_picture: 'https://i.pravatar.cc/150?img=57',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-010',
      external_id: 'pga-010',
      first_name: 'Brooks',
      last_name: 'Koepka',
      country: 'US',
      age: 34,
      ranking: 10,
      profile_picture: 'https://i.pravatar.cc/150?img=58',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-011',
      external_id: 'pga-011',
      first_name: 'Justin',
      last_name: 'Thomas',
      country: 'US',
      age: 31,
      ranking: 11,
      profile_picture: 'https://i.pravatar.cc/150?img=59',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'profile-012',
      external_id: 'pga-012',
      first_name: 'Max',
      last_name: 'Homa',
      country: 'US',
      age: 33,
      ranking: 12,
      profile_picture: 'https://i.pravatar.cc/150?img=60',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};

// Single player profile detail mock
export const playerProfileDetailMock = {
  data: {
    id: 'profile-001',
    external_id: 'pga-001',
    first_name: 'Tiger',
    last_name: 'Woods',
    country: 'US',
    age: 48,
    ranking: 1,
    profile_picture: 'https://i.pravatar.cc/150?img=12',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
};

// Error mocks
export const playerProfileNotFoundMock = {
  error: 'Player profile not found',
};

export const playerProfileServerErrorMock = {
  error: 'Failed to fetch player profiles',
};
