// Player profiles mock data
// Based on API schema: GET /api/player-profiles/
// Returns player groups with players array

export const playerProfilesListMock = {
  data: [
    {
      name: 'A',
      players: [
        {
          id: 'profile-001',
          external_id: 'pga-001',
          first_name: 'Tiger',
          last_name: 'Woods',
          country: 'US',
          age: 48,
          ranking: 1,
          profile_picture: 'https://i.pravatar.cc/150?img=12',
          group: 'A',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-002',
          external_id: 'pga-002',
          first_name: 'Rory',
          last_name: 'McIlroy',
          country: 'GB',
          age: 35,
          ranking: 2,
          profile_picture: 'https://i.pravatar.cc/150?img=13',
          group: 'A',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-003',
          external_id: 'pga-003',
          first_name: 'Jon',
          last_name: 'Rahm',
          country: 'ES',
          age: 29,
          ranking: 3,
          profile_picture: 'https://i.pravatar.cc/150?img=14',
          group: 'A',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
    {
      name: 'B',
      players: [
        {
          id: 'profile-004',
          external_id: 'pga-004',
          first_name: 'Scottie',
          last_name: 'Scheffler',
          country: 'US',
          age: 27,
          ranking: 4,
          profile_picture: 'https://i.pravatar.cc/150?img=15',
          group: 'B',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-005',
          external_id: 'pga-005',
          first_name: 'Viktor',
          last_name: 'Hovland',
          country: 'NO',
          age: 26,
          ranking: 5,
          profile_picture: 'https://i.pravatar.cc/150?img=33',
          group: 'B',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-006',
          external_id: 'pga-006',
          first_name: 'Dustin',
          last_name: 'Johnson',
          country: 'US',
          age: 40,
          ranking: 6,
          profile_picture: 'https://i.pravatar.cc/150?img=51',
          group: 'B',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
    {
      name: 'C',
      players: [
        {
          id: 'profile-007',
          external_id: 'pga-007',
          first_name: 'Collin',
          last_name: 'Morikawa',
          country: 'US',
          age: 27,
          ranking: 7,
          profile_picture: 'https://i.pravatar.cc/150?img=52',
          group: 'C',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-008',
          external_id: 'pga-008',
          first_name: 'Xander',
          last_name: 'Schauffele',
          country: 'US',
          age: 30,
          ranking: 8,
          profile_picture: 'https://i.pravatar.cc/150?img=56',
          group: 'C',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-009',
          external_id: 'pga-009',
          first_name: 'Patrick',
          last_name: 'Cantlay',
          country: 'US',
          age: 32,
          ranking: 9,
          profile_picture: 'https://i.pravatar.cc/150?img=57',
          group: 'C',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
    {
      name: 'D',
      players: [
        {
          id: 'profile-010',
          external_id: 'pga-010',
          first_name: 'Brooks',
          last_name: 'Koepka',
          country: 'US',
          age: 34,
          ranking: 10,
          profile_picture: 'https://i.pravatar.cc/150?img=58',
          group: 'D',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-011',
          external_id: 'pga-011',
          first_name: 'Justin',
          last_name: 'Thomas',
          country: 'US',
          age: 31,
          ranking: 11,
          profile_picture: 'https://i.pravatar.cc/150?img=59',
          group: 'D',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-012',
          external_id: 'pga-012',
          first_name: 'Max',
          last_name: 'Homa',
          country: 'US',
          age: 33,
          ranking: 12,
          profile_picture: 'https://i.pravatar.cc/150?img=60',
          group: 'D',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
    {
      name: 'E',
      players: [
        {
          id: 'profile-013',
          external_id: 'pga-013',
          first_name: 'Tommy',
          last_name: 'Fleetwood',
          country: 'GB',
          age: 33,
          ranking: 13,
          profile_picture: 'https://i.pravatar.cc/150?img=61',
          group: 'E',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-014',
          external_id: 'pga-014',
          first_name: 'Shane',
          last_name: 'Lowry',
          country: 'IE',
          age: 37,
          ranking: 14,
          profile_picture: 'https://i.pravatar.cc/150?img=62',
          group: 'E',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-015',
          external_id: 'pga-015',
          first_name: 'Tony',
          last_name: 'Finau',
          country: 'US',
          age: 35,
          ranking: 15,
          profile_picture: 'https://i.pravatar.cc/150?img=63',
          group: 'E',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
    {
      name: 'F',
      players: [
        {
          id: 'profile-016',
          external_id: 'pga-016',
          first_name: 'Hideki',
          last_name: 'Matsuyama',
          country: 'JP',
          age: 32,
          ranking: 16,
          profile_picture: 'https://i.pravatar.cc/150?img=64',
          group: 'F',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-017',
          external_id: 'pga-017',
          first_name: 'Cameron',
          last_name: 'Smith',
          country: 'AU',
          age: 31,
          ranking: 17,
          profile_picture: 'https://i.pravatar.cc/150?img=65',
          group: 'F',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-018',
          external_id: 'pga-018',
          first_name: 'Sungjae',
          last_name: 'Im',
          country: 'KR',
          age: 26,
          ranking: 18,
          profile_picture: 'https://i.pravatar.cc/150?img=66',
          group: 'F',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
    {
      name: 'G',
      players: [
        {
          id: 'profile-019',
          external_id: 'pga-019',
          first_name: 'Wyndham',
          last_name: 'Clark',
          country: 'US',
          age: 30,
          ranking: 19,
          profile_picture: 'https://i.pravatar.cc/150?img=67',
          group: 'G',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-020',
          external_id: 'pga-020',
          first_name: 'Brian',
          last_name: 'Harman',
          country: 'US',
          age: 37,
          ranking: 20,
          profile_picture: 'https://i.pravatar.cc/150?img=68',
          group: 'G',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-021',
          external_id: 'pga-021',
          first_name: 'Matt',
          last_name: 'Fitzpatrick',
          country: 'GB',
          age: 29,
          ranking: 21,
          profile_picture: 'https://i.pravatar.cc/150?img=69',
          group: 'G',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
    {
      name: 'H',
      players: [
        {
          id: 'profile-022',
          external_id: 'pga-022',
          first_name: 'Ludvig',
          last_name: 'Aberg',
          country: 'SE',
          age: 24,
          ranking: 22,
          profile_picture: 'https://i.pravatar.cc/150?img=70',
          group: 'H',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-023',
          external_id: 'pga-023',
          first_name: 'Sahith',
          last_name: 'Theegala',
          country: 'US',
          age: 26,
          ranking: 23,
          profile_picture: 'https://i.pravatar.cc/150?img=11',
          group: 'H',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-024',
          external_id: 'pga-024',
          first_name: 'Russell',
          last_name: 'Henley',
          country: 'US',
          age: 35,
          ranking: 24,
          profile_picture: 'https://i.pravatar.cc/150?img=10',
          group: 'H',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
    {
      name: 'I',
      players: [
        {
          id: 'profile-025',
          external_id: 'pga-025',
          first_name: 'Jordan',
          last_name: 'Spieth',
          country: 'US',
          age: 31,
          ranking: 25,
          profile_picture: 'https://i.pravatar.cc/150?img=17',
          group: 'I',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-026',
          external_id: 'pga-026',
          first_name: 'Adam',
          last_name: 'Scott',
          country: 'AU',
          age: 44,
          ranking: 26,
          profile_picture: 'https://i.pravatar.cc/150?img=18',
          group: 'I',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-027',
          external_id: 'pga-027',
          first_name: 'Jason',
          last_name: 'Day',
          country: 'AU',
          age: 37,
          ranking: 27,
          profile_picture: 'https://i.pravatar.cc/150?img=19',
          group: 'I',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
    {
      name: 'J',
      players: [
        {
          id: 'profile-028',
          external_id: 'pga-028',
          first_name: 'Rickie',
          last_name: 'Fowler',
          country: 'US',
          age: 36,
          ranking: 28,
          profile_picture: 'https://i.pravatar.cc/150?img=20',
          group: 'J',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-029',
          external_id: 'pga-029',
          first_name: 'Si Woo',
          last_name: 'Kim',
          country: 'KR',
          age: 29,
          ranking: 29,
          profile_picture: 'https://i.pravatar.cc/150?img=21',
          group: 'J',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          id: 'profile-030',
          external_id: 'pga-030',
          first_name: 'Keegan',
          last_name: 'Bradley',
          country: 'US',
          age: 38,
          ranking: 30,
          profile_picture: 'https://i.pravatar.cc/150?img=22',
          group: 'J',
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
    },
  ],
};

// Single player profile detail mock
export const playerProfileDetailMock = {
  data: {
    id: 'profile-001',
    external_id: 'pga-001',
    first_name: 'Tiger',
    last_name: 'Woods',
    country: 'US',
    age: 48,
    ranking: 1,
    profile_picture: 'https://i.pravatar.cc/150?img=12',
    group: 'A',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
};

// Error mocks
export const playerProfileNotFoundMock = {
  error: 'Player profile not found',
};

export const playerProfileServerErrorMock = {
  error: 'Failed to fetch player profiles',
};
